refactor the soft shutdown method

diff --git a/usr/bin/x735off b/usr/bin/x735off
--- a/usr/bin/x735off
+++ b/usr/bin/x735off
@@ -1,19 +1,36 @@
 #!/bin/bash
 
-BUTTON=20
-
-echo "$BUTTON" > /sys/class/gpio/export;
-echo "out" > /sys/class/gpio/gpio$BUTTON/direction
-echo "1" > /sys/class/gpio/gpio$BUTTON/value
+set -e
 
 SLEEP=${1:-4}
 
-re='^[0-9\.]+$'
-if ! [[ $SLEEP =~ $re ]] ; then
-   echo "error: sleep time not a number" >&2; exit 1
+readonly BTN_GPIO_PATH="/sys/class/gpio"
+readonly BUTTON=20
+
+readonly INVALID_CLI_ARG_TYPE="151"
+
+terminate() {
+    local -r msg=$1
+    local -r err_code=${2:-160}
+    echo "${msg}" >&2
+    exit "${err_code}"
+}
+
+if ! [[ $SLEEP =~ ^[0-9\.]+$ ]] ; then
+   terminate "error: sleep time not a number" "${INVALID_CLI_ARG_TYPE}"
 fi
 
-echo "Your device will shutting down in ${SLEEP} seconds..."
-/bin/sleep $SLEEP
 
-echo "0" > /sys/class/gpio/gpio$BUTTON/value
+# Main method
+function __main__ {
+  echo "$BUTTON" > /sys/class/gpio/export;
+  echo "out" > /sys/class/gpio/gpio$BUTTON/direction
+  echo "1" > /sys/class/gpio/gpio$BUTTON/value
+
+  echo "Your device will shutting down in ${SLEEP} seconds..."
+  /bin/sleep $SLEEP
+
+  echo "0" > /sys/class/gpio/gpio$BUTTON/value
+}
+
+__main__
